### ISSUE TITLE
Error 404 after installation - Missing Symlinks - Contao 4.3.4

### ISSUE THREAD

**Issue by emestrovicCTS** [madeyourday/contao-rocksolid-frontend-helper#20]
Just have installed Contao 4.3.4. and Rocksolid Frontend Helper but main.js and main-v4.css was missing.
(domain.com/en/bundles/rocksolidfrontendhelper/js/main.js)

After running `composer require madeyourday/contao-rocksolid-frontend-helper ^1.2.4`

I've got just this symlink

```
      Bundle                   Method / Error    
  ✔   ContaoCoreBundle         relative symlink  
  ✔   ContaoCommentsBundle     relative symlink  
  ✔   ContaoNewsletterBundle   relative symlink  
```

So probably you should check creating symlinks.

**Comment by ausi** [comment]
Please try to remove the *vendor/madeyourday/contao-rocksolid-frontend-helper* directory and reinstall the extension with `composer install --prefer-source`.
