### ISSUE TITLE
Aktivieren/Deaktivieren umtauschen

### ISSUE THREAD

**Issue by Xendiadyon** [madeyourday/contao-rocksolid-frontend-helper#25]
Aus UX-Sicht ist der Button zum Aktivieren/Deaktivieren genau falsch herum:
![image](https://user-images.githubusercontent.com/2657385/36976665-af1e1dfa-207e-11e8-9e18-decb68dd9485.png)

Man erwartet zuerst das "X" zu sehen, und als Tooltip: "Frontend-Editor nicht aktiv".
Wenn man dann drauf klickt, sollte der Haken kommen und der Tooltip "Frontend-Editor aktiv".

Vielleicht überlegt ihr euch mal, das umzudrehen?

**Comment by operatorone** [comment]
Finde ich eine gute Idee dies anzupassen. Ich muss auch jedesmal nachdenken wie rum es ist ;-)

**Comment by woerndl** [comment]
Da dieser Toggler eine Option, keine Aktion, triggert sollte er den Status zeigen, nicht das zu erwartende Ergebnis. Das folgt gleichzeitig der Logik die Contao für die Ein-/Ausblendenschaltfläche (= Auge) verwendet.

Wir sollten die Schaltfläche in einen Toggler mit Ein/Aus innerhalb des Kontrollelementes verwandeln.

![toggle-example](https://user-images.githubusercontent.com/930842/37332936-4dd8670a-26a8-11e8-88f2-8643dfa84151.jpg)

**Comment by ausi** [comment]
Wir könnten die Deaktivierung auch in das Hauptmenü verschieben und nach jedem Reload den Helper wieder automatisch aktivieren. Die Aktivieren/Deaktivieren-Funktion könnte von vielen Usern eher als störend empfunden werden wie sie aktuell funktioniert.

**Comment by Ernestopheles** [comment]
yupp

**Comment by Ernestopheles** [comment]
Ich finde den Vorschlag von woerndl sehr gut. zusätzlich würde ich die Switchfunktion anders benennen, denn es wird ja nur eine Teilfunktion de/aktiviert. Z.B. "Bearbeitungsleiste bei den Content-Elementen de/aktivieren"
