### ISSUE TITLE
Events-Liste: itemscope wird ausgegeben

### ISSUE THREAD

**Issue by Xendiadyon** [madeyourday/contao-rocksolid-frontend-helper#26]
Hallo :)

Bei der Eventliste wird fälschlicherweise der itemscope ausgegeben. D.h. hier gibt es wahrscheinlich einen Fehler beim Escapen der Anführungszeichen.
![image](https://user-images.githubusercontent.com/2657385/36976876-63cd54fa-207f-11e8-866b-6b4160ec605d.png)

```
<div class="event layout_list bygone  even first last cal_7  
data-frontend-helper="{&quot;template&quot;:&quot;event_list_home&quot;,&quot;templatePath&quot;:&quot;templates\/template\/event_list_home.html5&quot;,&quot;templateURL&quot;:&quot;\/contao?do=tpl_editor&amp;act=source&amp;id=templates%2Ftemplate%2Fevent_list_home.html5&amp;rt=0MHbh_R3Q3oXVdgIKmn-ZN1sE8NKeJQ90CMt98MvR7s&amp;rsfhr=1&quot;,&quot;templateLabel&quot;:&quot;Die Datei \&quot;event_list_home.html5\&quot; bearbeiten&quot;,&quot;toolbar&quot;:true,&quot;links&quot;:{&quot;be-module&quot;:{&quot;url&quot;:&quot;\/contao?do=calendar&amp;table=tl_content&amp;id=335&amp;rt=0MHbh_R3Q3oXVdgIKmn-ZN1sE8NKeJQ90CMt98MvR7s&amp;rsfhr=1&quot;,&quot;label&quot;:&quot;Kalender ID 335 bearbeiten&quot;,&quot;icon&quot;:&quot;system\/themes\/flexible\/icons\/settings.svg&quot;}}}">" itemscope itemtype="http://schema.org/Event">
[...]
```

Am Ende haben wir dort: `}}}">" itemscope itemtype="http://schema.org/Event">` stehen.

![image](https://user-images.githubusercontent.com/2657385/36977199-a12e8606-2080-11e8-9d3f-3737c2426640.png)

Ich hoffe, ihr könnt den Fehler dadurch finden.

**Comment by ausi** [comment]
Wie sieht der Quelltext aus wenn kein Benutzer im Backend angemeldet ist?

**Comment by Xendiadyon** [comment]
Ich sehe, worauf du hinaus willst.
```
<div class="event layout_list bygone even first last cal_7  >" itemscope itemtype="http://schema.org/Event">

<div class="header">
<h3 itemprop="name"><a href="unternehmen/news/newsreader/newsheadline-mit-etwas-text/"
```

Da war ein Fehler im Template, diese schließende spitze Klammer sollte da selbstverständlich nicht hin.

Ich habe das behoben, jetzt funktioniert alles. Ich bin mir nicht sicher, ob dieser dumme Fehler von dir abgefangen werden sollte; von mir aus kannst du schließen.

Danke, dass du mich auf den richtigen Pfad gebracht hast.

**Comment by ausi** [comment]
Theoretisch ist der HTML-Code valide, da das `>`-Zeichen in einem Attribut erlaubt ist.

Wenn sich der Fehler einfach beheben lässt werden wir das tun.

**Comment by ausi** [comment]
Behoben in Version 2.0.3.
