### ISSUE TITLE
body CSS-Klasse wird entfernt (Contao Version 4.4.14)

### ISSUE THREAD

**Issue by operatorone** [madeyourday/contao-rocksolid-frontend-helper#27]
Nach der Aktivierung des  Frontend Helper wird im gleichen Browser in dem das Backend geöfnet ist im Tab oder Fenster des Frontends am body die in den Seiten definierte CSS-Klasse entfernt und somit das Layout verändert. Schalte ich den Frontend Helper in meinem Profil aus, sieht alles gut aus.

**Comment by ausi** [comment]
Ich konnte den Fehler nicht reproduzieren.

Wie sieht der Quelltext des `<body>`-Tags mit und wie ohne aktiviertem Frontend-Helper aus?  
Bitte über *Rechte Maustaste › „Seitenquelltext anzeigen“* nachsehen, nicht über die Developer-Tools des Browsers.

**Comment by operatorone** [comment]
<body id="top" class='mac firefox gecko fx59 homer' itemscope itemtype="http://schema.org/WebPage">

**Comment by ausi** [comment]
Sind auch andere Erweiterungen installiert? Falls ja, verschwinden die Fehler wenn die anderen Erweiterungen deaktiviert werden?

**Comment by operatorone** [comment]
Folgende Erweiterungen sind noch installiert:
#   - alnv/prosearch : 1.1.0
#   - codefog/contao-cookiebar : 1.4.0
#   - dklemmt/contao_dk_mmenu : 2.0.1
#   - fritzmg/contao-lightcase : 2.0.1
#   - heimrichhannot/contao-hyphenator : 1.1.2
#   - hofff/contao-opengraph : 3.2.0
#   - ma3xl3/contao-easy-favicon : 2.0.0
#   - madeyourday/contao-rocksolid-antispam : v2.0.0
#   - madeyourday/contao-rocksolid-columns : v2.0.1
#   - madeyourday/contao-rocksolid-custom-elements : v2.2.3
#   - madeyourday/contao-rocksolid-frontend-helper : v2.0.2
#   - madeyourday/contao-rocksolid-icon-picker : v2.0.2
#   - markocupic/bootstrap_responsive_youtube_embed : 1.0.1
#   - mindbird/contao-uitotop : 2.0.0
#   - terminal42/contao-easy_themes : 2.2.6
#   - terminal42/contao-pageimage : 3.3.1

Gibt es eine Möglichkeit alle zeitweise zu deaktivieren?

**Comment by ausi** [comment]
Nein, aktuell gibt es keine Möglichkeit zur Deaktivierung einer Erweiterung, siehe contao/core#8770
