### ISSUE TITLE
Runtime Exception im app_dev mode

### ISSUE THREAD

**Issue by kgansberger** [madeyourday/contao-rocksolid-frontend-helper#28]
`Failed to start the session because headers have already been sent by ".../vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Response.php" at line 358.`

Liegt definitiv am Modul, beim Aufrufen einer Seite im Backend - komischerweise nicht immer.

**Comment by ausi** [comment]
Enthält die Fehlermeldung auch an welcher Stelle in welcher Datei das Problem verursacht wird?

**Comment by kgansberger** [comment]
ich habs mittlerweile deinstalliert, ich glaube es waren: 
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/9a580539ddc0364f6acca88f7074088c1a9d4cc2/src/BackendHooks.php#L50
und/oder
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/9a580539ddc0364f6acca88f7074088c1a9d4cc2/src/BackendHooks.php#L72

**Comment by ausi** [comment]
Ich konnte den Fehler nicht reproduzieren. Die beiden erwähnten Stellen werden über den `loadDataContainer`-Hook aufgerufen und sollten somit nicht nach einer Response ausgeführt werden.

**Comment by joeherold** [comment]
@ausi man merkt den fehler nicht sofort, da die fehler ausgabe unten nach dem backend dran-klebt

**Comment by joeherold** [comment]
@ausi ich hatte das problem auch schon

**Comment by ausi** [comment]
Ich konnte das Problem nun reproduzieren. Der `loadDataContainer`-Hook wird durch den CommandScheduler aufgerufen nachdem die Response abgesendet wurde. 

Der Fehler wurde mit 72513af15d3bd8bbbcecb85a4dd0b234f86cce7c behoben.
