### ISSUE TITLE
Link einfügen im Editor lädt Frontend-Seite mit Rocksolid Frontend Helper

### ISSUE THREAD

**Issue by wortberge** [madeyourday/contao-rocksolid-frontend-helper#30]
Hallo,

wenn ich im Editor einen Text erstelle und anschließend einen Link einfügen möchte, öffnet sich anstelle des Contao Seitenbaums eine Frontend-Seite mit dem Frontend Helper.

Contao v4.4.18
Frontend-Helper v2.0.2

**Comment by ausi** [comment]
Ich konnte den Fehler mit Contao 4.4.18 nicht reproduzieren. 

Verschwindet der Fehler wenn der Frontend-Helper über das Benutzerprofil deaktiviert wird, oder wenn die Erweiterung deinstalliert wird?

Wie lässt sich der Fehler Schritt für Schritt reproduzieren?

**Comment by wortberge** [comment]
Bitte entschuldige, dass ich nicht früher antworten konnte. 
Nachdem ich den Frontend-Helper entfernt und neu installiert hatte, trat das Problem nicht mehr auf.

Danke für die Hilfe!
