### ISSUE TITLE
FE edit sidebar should be resizable

### ISSUE THREAD

**Issue by Toflar** [madeyourday/contao-rocksolid-frontend-helper#32]
If you only edit text, it's fine but if you want to use something like a file picker, it becomes pretty unusable. Would be great if one could drag and make the sidebar bigger (and maybe store the size in a cookie or localstorage or something). Wdyt?

![screenshot-1](https://user-images.githubusercontent.com/481937/42084836-1622841c-7b8f-11e8-9678-8ee46361a864.png)

**Comment by ausi** [comment]
Implemented in ab9ea1755daf7554bb71603e5afe900af5ea1d1d

**Comment by Toflar** [comment]
Nice! Works like a charm!
