### ISSUE TITLE
Contao 4.5 - Frontend-Preview (Elemente sichtbar/unsichtbar schalten)

### ISSUE THREAD

**Issue by Sioweb** [madeyourday/contao-rocksolid-frontend-helper#34]
Hallo,

wir verwenden das Modul und haben gesehen, dass wir unsichtbare Element nicht anzeigen lassen können, über die entsprechende Option. Vermutlich liegt es daran, dass im Javascript das Cookie FE_PREVIEW gesetzt wird, was in Contao 4.5 wohl nicht mehr verwendet wird.

Wäre es möglich den Reload abzufangen und folgende Klasse anzustoßen? 

https://github.com/contao/contao/blob/master/core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php#L56

LG
Sascha

**Comment by ausi** [comment]
Behoben in Version 2.0.3.
