### ISSUE TITLE
Problem mit ESI-Fragmente

### ISSUE THREAD

**Issue by dmolineus** [madeyourday/contao-rocksolid-frontend-helper#37]
Seit Contao 4.5 lassen sich Module/Inhaltselemente ja auch als Fragemente definieren. Werden diese als esi gerendet, führt es dazu, dass der Frontend-Helper diese Tags erweitert und damit die ESI-Tags nicht mehr ersetzt werden.

Im Quelltext sieht es dann folgendermaßen aus:

```html
<esi data-frontend-helper="{&quot;toolbar&quot;:true,&quot;links&quot;:{&quot;fe-module&quot;:{&quot;url&quot;:&quot;\/contao?do=themes&amp;table=tl_module&amp;act=edit&amp;id=731&amp;rt=ZV_NVvl1iZNHoTFXNkgmbZFEUUGLEj14RokZ_498pC0&amp;rsfhr=1&quot;,&quot;label&quot;:&quot;Modul ID 731 (Layoutbereiche | DEFAULT | EFK | DE) bearbeiten&quot;}}}" :include="" src="/_fragment?_path=_scope%3Dfrontend%26moduleModel%3D731%26section%3Dright%26pageModel%3D3%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.frontend_module.hofff_content_references&amp;_hash=yqfeRbnNWxbY5eCylyUVLunLlXcakPBn90RfQbOG8Uc%3D">                  </esi>
```

Das Problem lässt sich z.B. durch die Verwendung von hofff/contao-content v.3 nachstellen (nicht unter app_dev.php, da hier keine ESI-Tags erstellt werden).

/cc @frontendschlampe

**Comment by ausi** [comment]
Sollte im master branch behoben sein.

**Comment by ausi** [comment]
Wenn kein Element gefunden wird fügt der Frontend-Helper ein `<span class="rsfh-dummy" data-frontend-helper="…">` ein um die Daten zu übermitteln. Eventuell könnten wir bei einem komplett leeren Element darauf verzichten. Ich werde das prüfen.

**Comment by ausi** [comment]
Bitte erneut den master Branch testen. Für leere Frontend-Module sollten nun keine Daten mehr ausgegeben werden.

**Comment by frontendschlampe** [comment]
yeah ... supi ... passt
