### ISSUE TITLE
Versionskonflikt

### ISSUE THREAD

**Issue by Anke** [madeyourday/contao-rocksolid-frontend-helper#41]
Hallo,

in Contao 4.9.x erhalte ich ab und zu eine "Versionskonflikt"-Meldung, wenn ich etwas im FE ändere. Ich habe noch nicht genau rausgefunden, unter welchen Umständen das genau passiert. Hat das Phänomen noch jemand?

Gruß,
Anke

**Comment by ausi** [comment]
Ein Versionskonflikt-Fehler ist uns nicht bekannt.

Bitte erstell unter https://my.rocksolidthemes.com/support ein Ticket und füge einen Screenshot der Fehlermeldung an.
