### ISSUE TITLE
XMLHttpRequest for contao/preview_switch of unpublished items

### ISSUE THREAD

**Issue by rabauss** [madeyourday/contao-rocksolid-frontend-helper#42]
In Contao 4.9 the link to the `contao/preview_switch` of unpublished items is not working anymore - generated here:
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/519ed500a582069baaa1bb9456039f706f7b7ab0/src/FrontendHooks.php#L286

The route call should be refactored to XMLHttpRequest - I guess somewhere here:
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/519ed500a582069baaa1bb9456039f706f7b7ab0/src/Resources/public/js/main.js#L433

**Comment by ausi** [comment]
Closed in favor of #43
