### ISSUE TITLE
Editing news under preview.php url let generate wrong xml ulr

### ISSUE THREAD

**Issue by Ainschy** [madeyourday/contao-rocksolid-frontend-helper#45]
When a user edit a news with frontend editing over the preview.php site. Contao generate wrong xml urls with preview.php in it.

**Comment by ausi** [comment]
Does this also happen if you manually go to `/preview.php/contao?do=news` on your website and edit a news article?

**Comment by Ainschy** [comment]
yes, same issue. Looks like a contao issue

**Comment by Ainschy** [comment]
Issue reported zu contao:  [Contao Issue #3099](https://github.com/contao/contao/issues/3099)
