### ISSUE TITLE
No editing possible on home page

### ISSUE THREAD

**Issue by Anke** [madeyourday/contao-rocksolid-frontend-helper#48]
Hallöchen,

I have several installations of Contao 4.11x and I notice that the editing buttons are visible on all pages except for the home page. Only when I add the page to the URL, i.e. calling https://www.domain.de/**index.html**, then the editing buttons do appear on the home page as well.

This only applies to the normal view; in preview mode it seems to be working. Anyone else noticing this behavior? 

Greetings, Anke

**Comment by ausi** [comment]
Do you have an enabled page cache?
You can look in the network tab of your browser and search for the `contao-cache` header to see if the response was delivered by the cache.

**Comment by Anke** [comment]
I'm not sure, but didn't disable the cache in Contao. The domains is https://www.ihretelefonzentrale.de/

**Comment by Anke** [comment]
Okay, I had the "always use the shared cache" option active. I disabled it and at the moment the FE-editor is there...
