### ISSUE TITLE
Contao 4.9x compatibility?

### ISSUE THREAD

**Issue by bi-datr** [madeyourday/contao-rocksolid-frontend-helper#55]
Will the extension work for Contao 4.9x in next few weeks, what is planned?

**Comment by bi-datr** [comment]
> Please use the version constraint `^2.0`

Thanks, worked now. So it wont work with ^2.2 constraint, right? Paket Manager tells now: Version v2.1.4 (v2.2.0 verfügbar)

**Comment by ausi** [comment]
> So it wont work with ^2.2 constraint, right?

Correct. Version 2.2 is only compatible with Contao 4.13 and 5.0.
