### ISSUE TITLE
Color Picker : Date selector not working

### ISSUE THREAD

**Issue by biowebfr** [madeyourday/contao-rocksolid-frontend-helper#56]
Contao 4.13.13
RockSolid Front end Helper 2.1

Hi,
I found that the color picker is not working when editing from the front with Front End Helper.
![image](https://user-images.githubusercontent.com/46192868/203587199-20bee4fa-2e60-4472-a192-b3dca8b7e147.png)

And so on with date selector.
![image](https://user-images.githubusercontent.com/46192868/203587645-b3534984-d691-45f6-a3c9-005d4a8593a3.png)

**Comment by biowebfr** [comment]
Ho I'm sorry I can't downgrade the project... :'(

**Comment by ausi** [comment]
Please upgrade to Contao 4.13.14 and test if this fixes the issue.

**Comment by biowebfr** [comment]
It works !!!! ;) 
Thanks a lot !
