### ISSUE TITLE
Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by Ernestopheles** [madeyourday/contao-rocksolid-frontend-helper#57]
Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 24899064 bytes) at ...vendor/madeyourday/contao-rocksolid-frontend-helper/src/FrontendHooks.php:946)

After Update contao to 4.13.19 (PHP 8.1)

**Comment by Ernestopheles** [comment]
This error occured after deinstalling a calendar extension whixh limited the number of weekly recurring events to 1. Therefore the website tried to list unlimited recurrencies of this event and this extension gave up first...

**Comment by ausi** [comment]
> Therefore the website tried to list unlimited recurrencies of this event

Unlimited data is not supported.
