### ISSUE TITLE
Certain operations won't save changes in preview mode

### ISSUE THREAD

**Issue by FlorinvV** [madeyourday/contao-rocksolid-frontend-helper#59]
Trying to move or delete elements while in preview mode show the changes in real time, won't save them though.

Easily reproducable by using the FE-helper in preview mode.

Tested on
Contao Version 4.13.25
madeyourday/contao-rocksolid-frontend-helper v2.2.0
PHP 8.0

**Comment by ausi** [comment]
Should be fixed with 5b5b0eb0887058dfd7e5a3d2d203df24ee39f34a in version 2.2.1.
