### ISSUE TITLE
C5.2: Inhaltselemente durch Redakteure nicht bearbeitbar

### ISSUE THREAD

**Issue by Anke** [madeyourday/contao-rocksolid-frontend-helper#63]
Hallöchen,

der FE Helper ist für den Benutzer aktiviert und dieser hat "nur Gruppenrechte". In den Gruppenrechten ist es egal, ob ich im Abschnitt RockSolid Frontend Helper alle Optionen aktiviere oder nur "Inhaltselemente" - im Frontend kann der Benutzer außer "Artikel bearbeiten" lediglich neue Inhaltelemente hinzufügen, aber vorhandene Inhaltelemente nicht bearbeiten, nicht einmal Text-Elemente - egal ob im Preview oder bei normaler Website-Ansicht.

In den Contao-Einstellungen sind die Standard-Zugriffsrechte auf den Benutzer und seine Gruppe eingestellt, als Autor ist in den Artikeln z.T. ebenfalls der Benutzer ausgewählt. Vergesse ich irgend etwas oder handelt es sich um einen Bug?

Grüße,
Anke

**Comment by ausi** [comment]
Ich konnte das beschriebene Problem mit den genannten Einstellungen nicht reproduzieren. Die Inhaltselemente konnten wie erwartet bearbeitet werden.

Welche Contao-Version und welche Version der Frontend-Helper-Erweiterung ist im Einsatz?

Bitte auch einen Screenshot posten der die fehlende Bearbeitungsmöglichkeit zeigt.

**Comment by Anke** [comment]
Ah, tut mir leid, mein Fehler! Habe das "Inhaltselemente einschränken" falsch verstanden und alles markiert, wo der Nutzer KEINEN Zugriff drauf haben soll.
Dank dir für deine Mühe!
